enum StartupScreenMode { 
  LOGIN, 
  SINGUP1OF3, 
  SINGUP2OF3, 
  SINGUP3OF3, 
  FORGOTUSERNAME, 
  FORGOTUSERNAMECONFIRMATION,
  FORGOTPASSWORD,
  FORGOTPASSWORDPINVERIFICATION,
  FORGOTPASSWORDCHANGEPASSWORD,
  FORGOTPASSWORDCONFIRMATION,
}